### PR TITLE
OTBR modules

### PR DESCRIPTION
**Pull request by lesinga**
OTBR: modules/scripts
DIscord: lesinga#5072

### CODE REVIEW

**Comment by OTCv8** [comment]
Good job, but you need to change few things:
- It's not only for version 12.52, you need to support older versions, use g_game.getClientVersion() to check version (return for example 1240)
- Don't implement store, it's implemented in game_store
Implement that, test it on some otservbr-global server and I'll send you $100 within few days, after it's tested by players

**Comment by Beats-Dh** [comment]
I did the tests using otservbr-global, load the char list but do not enter the game. At the client terminal it doesn't give an error but at the server the error is related to the RSA key.

**Comment by aurelion5670** [comment]
I think that the problem is due to the protocolgamesend.cpp file that kondra modified:
- https://github.com/OTCv8/otclientv8/commit/f149ea61f1b14f6b6ddedbf8c17c388bedb320fe

On older versions that bug doesn't exist.

**Comment by lesinga** [comment]
> I did the tests using otservbr-global, load the char list but do not enter the game. At the client terminal it doesn't give an error but at the server the error is related to the RSA key.

With some changes on the protocolgame.cpp and iologindata.cpp you can by pass this error.  Connecting to the otbr as client 10 version there is no problem atm, but with 12, at least 12.60, there are several glitches on the UI. As far as i know, nothing to do with this PR.
image

**Comment by Beats-Dh** [comment]
sí, soy un profano en el tema de tal modificación

**Comment by OTCv8** [comment]
add me on discord

**Pull request closed without merging**
